name             = "dzhun"
main             = "worker.js"
compatibility_date = "2024-09-23"
workers_dev      = true

[[routes]]
pattern = "api.dzhun.com.cn/*"
zone_name = "dzhun.com.cn"

# KV 命名空间：存储支付订单和 pay token
[[kv_namespaces]]
binding = "ORDERS"
id      = "49742c254d0f45ef95e1e56073a0e7c9"

# KV 命名空间：OCR 结果缓存（24小时）
[[kv_namespaces]]
binding = "CACHE"
id      = "f0b05a459aea449380a05d857f6f8a21"
