name             = "dzhun"
main             = "worker.js"
compatibility_date = "2024-09-23"

# KV 命名空间：存储支付订单和 pay token
[[kv_namespaces]]
binding = "ORDERS"
id      = "49742c254d0f45ef95e1e56073a0e7c9"
